In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'C:\Users\prafu\Music\ML-Learning\ML-Playground\Projects\Sample_Dataset\wcplayerstatistics.csv')
df.head()

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
0,1,Brenden Aaronson,MF,us United States,25.0,1.eng Leeds United,2000.0,1.0,1.0,76.0,...,0.0,0.0,0.0,0.0,5bc43860,0.0,0.0,0.0,0.0,0.0
1,2,Thelo Aasgaard,MF,no Norway,24.0,1.sct Rangers,2002.0,1.0,1.0,90.0,...,0.0,0.0,0.0,0.0,c88a28b9,0.0,1.0,1.0,1.0,1.0
2,3,Hamza Abdelkarim,FW,eg Egypt,18.0,4.es Barcelona B,2008.0,4.0,0.0,60.0,...,0.0,0.0,0.0,0.0,057d8f12,0.0,0.0,0.0,0.0,0.0
3,4,Hossam Abdelmaguid,DF,eg Egypt,25.0,1.eg Zamalek SC,2001.0,2.0,0.0,59.0,...,0.0,0.0,0.0,0.0,accbfc94,0.0,0.0,0.0,0.0,0.0
4,5,Mohamed Abdelmonem,DF,eg Egypt,27.0,1.fr Nice,1999.0,2.0,1.0,14.0,...,0.0,0.0,0.0,0.0,bff15d74,0.0,0.0,0.0,0.0,0.0

In [3]:
df.shape

(1039, 25)

In [4]:
df.columns

Index(['Rk', 'Player', 'Pos', 'Squad', 'Age', 'Club', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY',
       'CrdR', 'PlayerID', 'AstPer90', 'G+APer90', 'GlsPer90', 'G-PKPer90',
       'G+A-PKPer90'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1039 entries, 0 to 1038
Data columns (total 25 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Rk           1039 non-null   int64
 1   Player       1039 non-null   str
 2   Pos          1039 non-null   str
 3   Squad        1039 non-null   str
 4   Age          1039 non-null   float64
 5   Club         1036 non-null   str
 6   Born         1039 non-null   float64
 7   MP           1039 non-null   float64
 8   Starts       1039 non-null   float64
 9   Min          1039 non-null   float64
 10  90s          1039 non-null   float64
 11  Gls          1039 non-null   float64
 12  Ast          1039 non-null   float64
 13  G+A          1039 non-null   float64
 14  G-PK         1039 non-null   float64
 15  PK           1039 non-null   float64
 16  PKatt        1039 non-null   float64
 17  CrdY         1039 non-null   float64
 18  CrdR         1039 non-null   float64
 19  PlayerID     1039 non-null   str
 20  AstPer90     1039 non-null   float64
 21  G+APer90     1039 non-null   float64
 22  GlsPer90     1039 non-null   float64
 23  G-PKPer90    1039 non-null   float64
 24  G+A-PKPer90  1039 non-null   float64
dtypes: float64(19), int64(1), str(5)
memory usage: 253.6 KB

In [6]:
df.isnull()

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1035,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1036,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1037,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1038,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df.isnull().sum()

Rk             0
Player         0
Pos            0
Squad          0
Age            0
Club           3
Born           0
MP             0
Starts         0
Min            0
90s            0
Gls            0
Ast            0
G+A            0
G-PK           0
PK             0
PKatt          0
CrdY           0
CrdR           0
PlayerID       0
AstPer90       0
G+APer90       0
GlsPer90       0
G-PKPer90      0
G+A-PKPer90    0
dtype: int64

In [8]:
df.describe()

,Rk,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
count,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000
mean,520.000000,27.463908,1998.022137,3.164581,2.202117,203.474495,2.259865,0.283927,0.215592,0.499519,0.268527,0.015399,0.021174,0.259865,0.014437,0.089923,0.229865,0.139875,0.134235,0.224216
std,300.077768,4.198173,4.196578,1.664215,1.873030,158.361191,1.757987,0.834724,0.590310,1.169519,0.786495,0.130781,0.162869,0.511747,0.119341,0.314995,1.043094,0.989740,0.985793,1.039396
min,1.000000,17.000000,1985.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,260.500000,24.000000,1995.000000,2.000000,1.000000,71.000000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,520.000000,27.000000,1998.000000,3.000000,2.000000,180.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,779.500000,30.000000,2001.000000,4.000000,3.000000,288.000000,3.200000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.230000,0.000000,0.000000,0.210000
max,1039.000000,41.000000,2008.000000,8.000000,8.000000,810.000000,9.000000,10.000000,7.000000,14.000000,9.000000,2.000000,2.000000,3.000000,1.000000,4.500000,30.000000,30.000000,30.000000,30.000000

In [9]:
print(f"There are {len(df['Squad'].unique())} teams in the tournament. \n The teams are:")
df['Squad'].unique()

There are 48 teams in the tournament.
 The teams are:

<ArrowStringArray>
[ 'us United States',         'no Norway',          'eg Egypt',
        'tn Tunisia',   'sa Saudi Arabia',     'uz Uzbekistan',
          'qa Qatar',         'jo Jordan',      'sct Scotland',
   'za South Africa',          'ht Haiti',  'ci Côte d'Ivoire',
          'gh Ghana',    'ch Switzerland',        'uy Uruguay',
         'ca Canada',        'dz Algeria',    'nl Netherlands',
        'tr Türkiye',         'fr France',        'at Austria',
    'ba Bosnia–Herz',        'ec Ecuador',       'py Paraguay',
           'iq Iraq',         'se Sweden',        'ir IR Iran',
         'br Brazil',      'ar Argentina',         'mx Mexico',
        'ma Morocco',         'pa Panama',        'de Germany',
       'eng England',        'cw Curaçao',       'pt Portugal',
     'cv Cabo Verde',       'co Colombia',          'es Spain',
       'cd Congo DR',        'hr Croatia',      'au Australia',
    'nz New Zealand',        'sn Senegal',        'be Belgium',
 'kr Korea Republic',        'cz Czechia',          'jp Japan']
Length: 48, dtype: str

**Basic Questions**

- Display the first 10 rows.
- Display the last 15 rows.
- Find the shape of the dataset.
- Display all column names.
- Display data types of every column.
- Find how many numerical and categorical columns exist.
- Find missing values in every column.
- Display basic statistics of numerical columns.
- Display basic statistics of categorical columns.
- Check whether duplicate rows exist.

In [10]:
df.head(10)

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
0,1,Brenden Aaronson,MF,us United States,25.0,1.eng Leeds United,2000.0,1.0,1.0,76.0,...,0.0,0.0,0.0,0.0,5bc43860,0.0,0.0,0.0,0.0,0.0
1,2,Thelo Aasgaard,MF,no Norway,24.0,1.sct Rangers,2002.0,1.0,1.0,90.0,...,0.0,0.0,0.0,0.0,c88a28b9,0.0,1.0,1.0,1.0,1.0
2,3,Hamza Abdelkarim,FW,eg Egypt,18.0,4.es Barcelona B,2008.0,4.0,0.0,60.0,...,0.0,0.0,0.0,0.0,057d8f12,0.0,0.0,0.0,0.0,0.0
3,4,Hossam Abdelmaguid,DF,eg Egypt,25.0,1.eg Zamalek SC,2001.0,2.0,0.0,59.0,...,0.0,0.0,0.0,0.0,accbfc94,0.0,0.0,0.0,0.0,0.0
4,5,Mohamed Abdelmonem,DF,eg Egypt,27.0,1.fr Nice,1999.0,2.0,1.0,14.0,...,0.0,0.0,0.0,0.0,bff15d74,0.0,0.0,0.0,0.0,0.0
5,6,Ali Abdi,DF,tn Tunisia,32.0,1.fr Nice,1993.0,3.0,3.0,269.0,...,0.0,0.0,0.0,0.0,ad7cdb35,0.0,0.0,0.0,0.0,0.0
6,7,Saud Abdulhamid,DF,sa Saudi Arabia,26.0,1.fr Lens,1999.0,3.0,3.0,269.0,...,0.0,0.0,1.0,0.0,caa254e4,0.0,0.0,0.0,0.0,0.0
7,8,Abdulla Abdullaev,DF,uz Uzbekistan,28.0,1.ae Dibba Al Fujairah,1997.0,2.0,2.0,180.0,...,0.0,0.0,0.0,0.0,03053fbf,0.0,0.0,0.0,0.0,0.0
8,9,Yusuf Abdurisag,FW,qa Qatar,26.0,1.qa Al-Wakrah,1999.0,2.0,2.0,98.0,...,0.0,0.0,0.0,0.0,13c8f40b,0.0,0.0,0.0,0.0,0.0
9,10,Husam Abu Dahab,DF,jo Jordan,26.0,1.kw Al-Salmiya SC,2000.0,2.0,2.0,178.0,...,0.0,0.0,1.0,0.0,300aaeb6,0.0,0.0,0.0,0.0,0.0

In [11]:
df.iloc[-15:]

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
1024,1025,Utkir Yusupov,GK,uz Uzbekistan,35.0,1.uz Navbahor,1991.0,1.0,1.0,90.0,...,0.0,0.0,0.0,0.0,31caffaf,0.00,0.00,0.00,0.00,0.00
1025,1026,Warren Zaïre-Emery,MF,fr France,20.0,1.fr PSG,2006.0,2.0,1.0,110.0,...,0.0,0.0,0.0,0.0,6b9960cf,0.00,0.00,0.00,0.00,0.00
1026,1027,Denis Zakaria,DF,ch Switzerland,29.0,1.fr Monaco,1996.0,4.0,4.0,357.0,...,0.0,0.0,2.0,0.0,384d58d9,0.00,0.00,0.00,0.00,0.00
1027,1028,Jaroslav Zelený,MF,cz Czechia,33.0,1.cz Sparta Prague,1992.0,2.0,1.0,126.0,...,0.0,0.0,0.0,0.0,bc647827,0.00,0.00,0.00,0.00,0.00
1028,1029,Alejandro Zendejas,FWMF,us United States,28.0,1.mx América,1998.0,1.0,0.0,14.0,...,0.0,0.0,0.0,0.0,d717b80e,0.00,0.00,0.00,0.00,0.00
1029,1030,Besfort Zeneli,MF,se Sweden,23.0,1.be Union SG,2002.0,2.0,0.0,60.0,...,0.0,0.0,0.0,0.0,6be253bf,0.00,0.00,0.00,0.00,0.00
1030,1031,Ramiz Zerrouki,MF,dz Algeria,28.0,1.nl Twente,1998.0,3.0,2.0,111.0,...,0.0,0.0,1.0,0.0,c762b1a6,0.00,0.00,0.00,0.00,0.00
1031,1032,Luca Zidane,GK,dz Algeria,28.0,2.es Granada,1998.0,3.0,3.0,270.0,...,0.0,0.0,0.0,0.0,c818c4d9,0.00,0.00,0.00,0.00,0.00
1032,1033,Mostafa Ziko,FWMF,eg Egypt,29.0,1.eg Pyramids FC,1997.0,5.0,5.0,370.0,...,0.0,0.0,0.0,0.0,68ff8437,0.24,0.73,0.49,0.49,0.73
1033,1034,David Zima,DF,cz Czechia,25.0,1.cz Slavia Prague,2000.0,1.0,0.0,13.0,...,0.0,0.0,0.0,0.0,acf7e795,0.00,0.00,0.00,0.00,0.00
1034,1035,Zizo,MF,eg Egypt,30.0,1.eg Al Ahly,1996.0,4.0,0.0,56.0,...,0.0,0.0,0.0,0.0,c6415ba9,0.00,0.00,0.00,0.00,0.00
1035,1036,Martín Zubimendi,MF,es Spain,27.0,1.eng Arsenal,1999.0,1.0,0.0,22.0,...,0.0,0.0,0.0,0.0,3ee0dd59,0.00,0.00,0.00,0.00,0.00
1036,1037,Themba Zwane,FWMF,za South Africa,36.0,1.za Sundowns,1989.0,1.0,0.0,23.0,...,0.0,0.0,0.0,1.0,c6f21aa8,0.00,0.00,0.00,0.00,0.00
1037,1038,Martin Ødegaard,MF,no Norway,27.0,1.eng Arsenal,1998.0,5.0,5.0,470.0,...,0.0,0.0,0.0,0.0,79300479,0.77,0.77,0.00,0.00,0.77
1038,1039,Leo Østigård,DF,no Norway,26.0,1.it Genoa,1999.0,5.0,1.0,146.0,...,0.0,0.0,0.0,0.0,b35a7399,0.00,0.62,0.62,0.62,0.62

In [12]:
df.shape

(1039, 25)

In [14]:
print(f"All the column names are: \n{df.columns}")

All the column names are:
Index(['Rk', 'Player', 'Pos', 'Squad', 'Age', 'Club', 'Born', 'MP', 'Starts',
       'Min', '90s', 'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'CrdY',
       'CrdR', 'PlayerID', 'AstPer90', 'G+APer90', 'GlsPer90', 'G-PKPer90',
       'G+A-PKPer90'],
      dtype='str')

In [21]:
print("Datatype of each Column")
df.dtypes

Datatype of each Column

Rk               int64
Player             str
Pos                str
Squad              str
Age            float64
Club               str
Born           float64
MP             float64
Starts         float64
Min            float64
90s            float64
Gls            float64
Ast            float64
G+A            float64
G-PK           float64
PK             float64
PKatt          float64
CrdY           float64
CrdR           float64
PlayerID           str
AstPer90       float64
G+APer90       float64
GlsPer90       float64
G-PKPer90      float64
G+A-PKPer90    float64
dtype: object

In [24]:
df.dtypes.value_counts()

float64    19
str         5
int64       1
Name: count, dtype: int64

In [22]:
num_cols = df.select_dtypes(include='number')
cat_cols = df.select_dtypes(include='object')

print("Number of numerical columns:", num_cols.shape[1])
print("Number of categorical columns:", cat_cols.shape[1])

Number of numerical columns: 20
Number of categorical columns: 5

In [33]:
df.isnull().sum()

Rk             0
Player         0
Pos            0
Squad          0
Age            0
Club           3
Born           0
MP             0
Starts         0
Min            0
90s            0
Gls            0
Ast            0
G+A            0
G-PK           0
PK             0
PKatt          0
CrdY           0
CrdR           0
PlayerID       0
AstPer90       0
G+APer90       0
GlsPer90       0
G-PKPer90      0
G+A-PKPer90    0
dtype: int64

In [32]:
df.isnull().sum()[df.isnull().sum() > 0]

Club    3
dtype: int64

In [28]:
df[df.isnull().any(axis=1)]

,Rk,Player,Pos,Squad,Age,Club,Born,MP,Starts,Min,...,PK,PKatt,CrdY,CrdR,PlayerID,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
63,64,Abdulelah Al-Amri,DF,sa Saudi Arabia,29.0,NaN,1997.0,3.0,3.0,239.0,...,0.0,0.0,1.0,0.0,fd0affe3,0.0,0.38,0.38,0.38,0.38
372,373,Aziz Gʻaniyev,MF,uz Uzbekistan,28.0,NaN,1998.0,2.0,1.0,122.0,...,0.0,0.0,0.0,0.0,0c492054,0.0,0.00,0.00,0.00,0.00
521,522,Mohanad Lasheen,MF,eg Egypt,30.0,NaN,1996.0,4.0,4.0,359.0,...,0.0,0.0,2.0,0.0,8c041c7d,0.0,0.00,0.00,0.00,0.00

In [36]:
print(f"Basic Statistics for numerical Columns:")
df.describe()

Basic Statistics for numerical Columns:

,Rk,Age,Born,MP,Starts,Min,90s,Gls,Ast,G+A,G-PK,PK,PKatt,CrdY,CrdR,AstPer90,G+APer90,GlsPer90,G-PKPer90,G+A-PKPer90
count,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000,1039.000000
mean,520.000000,27.463908,1998.022137,3.164581,2.202117,203.474495,2.259865,0.283927,0.215592,0.499519,0.268527,0.015399,0.021174,0.259865,0.014437,0.089923,0.229865,0.139875,0.134235,0.224216
std,300.077768,4.198173,4.196578,1.664215,1.873030,158.361191,1.757987,0.834724,0.590310,1.169519,0.786495,0.130781,0.162869,0.511747,0.119341,0.314995,1.043094,0.989740,0.985793,1.039396
min,1.000000,17.000000,1985.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,260.500000,24.000000,1995.000000,2.000000,1.000000,71.000000,0.800000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,520.000000,27.000000,1998.000000,3.000000,2.000000,180.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,779.500000,30.000000,2001.000000,4.000000,3.000000,288.000000,3.200000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.230000,0.000000,0.000000,0.210000
max,1039.000000,41.000000,2008.000000,8.000000,8.000000,810.000000,9.000000,10.000000,7.000000,14.000000,9.000000,2.000000,2.000000,3.000000,1.000000,4.500000,30.000000,30.000000,30.000000,30.000000

In [37]:
print("Basic Stats for categorical Column: ")
df.describe(include='object')

Basic Stats for categorical Column:

                  Player   Pos      Squad                   Club  PlayerID
count               1039  1039       1039                   1036      1039
unique              1039     9         48                    386      1039
top     Brenden Aaronson    MF  no Norway  1.eng Manchester City  5bc43860
freq                   1   344         25                     18         1

In [41]:
#Whether duplicate rows exits
df.duplicated().value_counts()

False    1039
Name: count, dtype: int64