# Data Frame

A DataFrame is a **two-dimensional labeled data structure** in Pandas that stores data in rows and columns.  
It can hold multiple data types in different columns, similar to a spreadsheet or SQL table.

### Characteristics
- Two-dimensional (rows and columns)
- Mutable (can add, remove, or modify data)
- Supports heterogeneous data types
- Each column is a Pandas Series
- Row labels are called **index**
- Column labels are called **columns**

### Series vs DataFrame

| Series | DataFrame |
|--------|-----------|
| One-dimensional | Two-dimensional |
| Single column | Multiple columns |
| One index | Rows and columns |
| Can store one data type | Different columns can have different data types |

In [38]:
import pandas as pd
import numpy as np

### Creating a Dataframe

A DataFrame can be created from:

- Dictionary
- List of Lists
- NumPy Array
- List of Dictionaries
- CSV / Excel / SQL files

`Syntax` : pd.Dataframe( *data*, index = , columns = , dtype = )

| Parameter | Description |
|-----------|-------------|
| `data` | Dictionary, list, NumPy array, Series, or another DataFrame |
| `index` | Labels for the rows |
| `columns` | Labels for the columns |
| `dtype` | Specifies the data type for all columns (if possible) |

**Dictionary** 
- Creating dataframe from a dictionary, key becomes the header

In [39]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

**List**  
- Creating dataframe from a list, header are default set as index  
- For header, columns = *list  having column title* is added in the function

In [40]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

In [41]:
columns=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=columns, index=['First','Second','Third','Forth'])
df2

         Name  Age      City  Salary
First    John   28  New York   65000
Second   Anna   34     Paris   70000
Third   Peter   29    Berlin   62000
Forth   Linda   42    London   85000

**Reading Data**

Pandas provides built-in functions to read data from different file formats and databases into a DataFrame.

| Function | Reads From |
|----------|------------|
| `pd.read_csv()` | CSV file (`.csv`) |
| `pd.read_excel()` | Excel file (`.xlsx`, `.xls`) |
| `pd.read_json()` | JSON file (`.json`) |
| `pd.read_sql()` | SQL database or SQL query |

In [42]:
df3 = pd.read_csv(r"C:\Users\prafu\Music\ML-Learning\ML-Playground\Pandas\Practice_Datasets\anime.csv")

In [43]:
df3

    Rank                                              Title  Score
0      1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1      2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2      3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3      4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4      5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05
5      6  Gintama'TV (51 eps)Apr 2011 - Mar 2012534,105 ...   9.04
6      7  Gintama: The FinalMovie (1 eps)Jan 2021 - Jan ...   9.04
7      8  Hunter x Hunter TV (148 eps)Oct 2011 - Sep 201...   9.04
8      9  Kaguya-sama wa Kokurasetai: Ultra RomanticTV (...   9.04
9     10  Gintama': EnchousenTV (13 eps)Oct 2012 - Mar 2...   9.03
10    11  Shingeki no Kyojin: The Final Season - Kankets...   9.03
11    12  Ginga Eiyuu DensetsuOVA (110 eps)Jan 1988 - Ma...   9.02
12    13  Bleach: Sennen Kessen-hen - Ketsubetsu-tanTV (...   8.99
13    14  Fruits Basket: The FinalTV (13 eps)Apr 2021 - ...   8.99
14    15  Gintama.TV (12 eps)Jan 2017 - Mar 2017302,232 ...   8.98
15    16  GintamaTV (201 eps)Apr 2006 - Mar 20101,034,41...   8.94
16    17  Koe no KatachiMovie (1 eps)Sep 2016 - Sep 2016...   8.94
17    18  3-gatsu no Lion 2nd SeasonTV (22 eps)Oct 2017 ...   8.93
18    19  Clannad: After StoryTV (24 eps)Oct 2008 - Mar ...   8.93
19    20  Code Geass: Hangyaku no Lelouch R2TV (25 eps)A...   8.91
20    21  Gintama Movie 2: Kanketsu-hen - Yorozuya yo Ei...   8.91
21    22  Violet Evergarden MovieMovie (1 eps)Sep 2020 -...   8.89
22    23  Owarimonogatari 2nd SeasonTV (7 eps)Aug 2017 -...   8.88
23    24  Gintama.: Shirogane no Tamashii-hen - Kouhan-s...   8.88
24    25  MonsterTV (74 eps)Apr 2004 - Sep 20051,041,081...   8.87
25    26  Kimi no Na wa.Movie (1 eps)Aug 2016 - Aug 2016...   8.84
26    27  Kaguya-sama wa Kokurasetai: First Kiss wa Owar...   8.84
27    28  Bocchi the Rock!TV (12 eps)Oct 2022 - Dec 2022...   8.83
28    29  The First Slam DunkMovie (1 eps)Dec 2022 - Dec...   8.83
29    30  Vinland Saga Season 2TV (24 eps)Jan 2023 - Jun...   8.82
30    31  Jujutsu Kaisen 2nd SeasonTV (23 eps)Jul 2023 -...   8.82
31    32  Gintama.: Shirogane no Tamashii-henTV (12 eps)...   8.81
32    33  Kingdom 3rd SeasonTV (26 eps)Apr 2020 - Oct 20...   8.81
33    34  Mob Psycho 100 IITV (13 eps)Jan 2019 - Apr 201...   8.80
34    35  Shingeki no Kyojin: The Final SeasonTV (16 eps...   8.80
35    36  Kimetsu no Yaiba: Yuukaku-henTV (11 eps)Dec 20...   8.79
36    37  Kizumonogatari III: Reiketsu-henMovie (1 eps)J...   8.79
37    38  "Oshi no Ko"TV (11 eps)Apr 2023 - Jun 2023645,...   8.79
38    39  Haikyuu!! Karasuno Koukou vs. Shiratorizawa Ga...   8.78
39    40  Sen to Chihiro no KamikakushiMovie (1 eps)Jul ...   8.78
40    41  Monogatari Series: Second SeasonTV (26 eps)Jul...   8.77
41    42  Shingeki no Kyojin: The Final Season Part 2TV ...   8.77
42    43  Hajime no IppoTV (75 eps)Oct 2000 - Mar 200255...   8.76
43    44  Cowboy BebopTV (26 eps)Apr 1998 - Apr 19991,79...   8.75
44    45  Kingdom 4th SeasonTV (26 eps)Apr 2022 - Oct 20...   8.75
45    46  Vinland SagaTV (24 eps)Jul 2019 - Dec 20191,40...   8.74
46    47  Mushishi Zoku Shou 2nd SeasonTV (10 eps)Oct 20...   8.73
47    48  Shouwa Genroku Rakugo Shinjuu: Sukeroku Futata...   8.72
48    49  Mob Psycho 100 IIITV (12 eps)Oct 2022 - Dec 20...   8.71
49    50  Rurouni Kenshin: Meiji Kenkaku Romantan - Tsui...   8.71

### Selecting and Indexing of columns

- For one column a list containing Column name is required; returns a Series.
- For more than one list of list is required; returns dataframe

`Syntax` : *data_frame*[ *Column(s)* ]

In [44]:
df2["Name"]

First      John
Second     Anna
Third     Peter
Forth     Linda
Name: Name, dtype: str

In [45]:
df2[["Name","Age"]]

         Name  Age
First    John   28
Second   Anna   34
Third   Peter   29
Forth   Linda   42

### Creating a new Columns

`Syntax` : *data_frame*["*Column_header* "] = [*list containing values*]

In [46]:
df2["Designation"]=["Doctor","Eng","Doctor","Eng"]
df2

         Name  Age      City  Salary Designation
First    John   28  New York   65000      Doctor
Second   Anna   34     Paris   70000         Eng
Third   Peter   29    Berlin   62000      Doctor
Forth   Linda   42    London   85000         Eng

### Removing Rows or Columns

`Syntax` : *data_frame*.drop("*Column_name or Row_label*",axis=....)

drop() just makes a copy of the dataframe rather than doing operations on the actual dataframe

Axis

- `axis=0` → Rows
- `axis=1` → Columns
 
inplace

- `False` (Default) → Returns a new DataFrame.
- `True` → Modifies the original DataFrame.

In [47]:
df2.drop("Designation", axis=1)

         Name  Age      City  Salary
First    John   28  New York   65000
Second   Anna   34     Paris   70000
Third   Peter   29    Berlin   62000
Forth   Linda   42    London   85000

In [48]:
df2

         Name  Age      City  Salary Designation
First    John   28  New York   65000      Doctor
Second   Anna   34     Paris   70000         Eng
Third   Peter   29    Berlin   62000      Doctor
Forth   Linda   42    London   85000         Eng

In [49]:
df2.drop("Designation", axis=1, inplace= True)

In [50]:
df2

         Name  Age      City  Salary
First    John   28  New York   65000
Second   Anna   34     Paris   70000
Third   Peter   29    Berlin   62000
Forth   Linda   42    London   85000

### Selecting a row
- loc -> location
- iloc ->index location

In [ ]:
df.loc[0]

Name          John
Age             28
City      New York
Salary       65000
Name: 0, dtype: object

In [ ]:
df.iloc[1]

Name       Anna
Age          34
City      Paris
Salary    70000
Name: 1, dtype: object

**Selecting subsets of rows and columns**

*data_frame*.loc[[*index of rows*]] [[*Column_ header*]]

In [ ]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
df.loc[[0,1]][["City","Salary"]]

       City  Salary
0  New York   65000
1     Paris   70000

In [ ]:
df.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   29
3  Linda   42

### Conditional Filtering

Conditional filtering is used to select rows from a DataFrame that satisfy a specified condition.

`Syntax` : *dataframe*[*dataframe['Column_Name'] condition*]

In [ ]:
df2

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [ ]:
#Display data of age > 30
df2[df2["Age"] > 30]

    Name  Age    City  Salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [ ]:
df2[(df2["Age"] > 30) & (df2["City"]== "Paris")]

   Name  Age   City  Salary
1  Anna   34  Paris   70000