In [73]:
import numpy as np
import pandas as pd

*Loading Data*

In [74]:
df = pd.read_csv(r"C:\Users\prafu\Music\ML-Learning\ML-Playground\Pandas\Practice_Datasets\anime.csv")

In [75]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

**Create a new column for No of Episodes**

In [76]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

*Filtering no of episdoes from title*  
As enclosed inside "()"

In [77]:
def extract_episodes(txt):
    check=False
    data = ""
    for i in txt:
        if i== ")":
            check = False
            return data
        if check == True:
            data += i
        if i=="(":
            check=True

In [78]:
#Applying the funciton
df["Episodes"] = df["Title"].apply(extract_episodes)

In [79]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

Remove " eps" from Episodes  
Type conversion from str to int

In [80]:

df["Episodes"]=df["Episodes"].str.replace(" eps","").astype(int)

In [81]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

New column for time stamps

In [82]:
df.loc[1]["Title"]

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

In [83]:
def extraction_time(txt):
    check = False
    time = ""
    for i in range(len(txt)):
        if txt[i] == ")":
            for j in range(i+1,i+20):
                time += txt[j]
            return time

In [84]:
df["Total Time"]= df["Title"].apply(extraction_time)

In [85]:
df.head()

,Rank,Title,Score,Episodes,Total Time
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

Total Time Duration of a Anime

In [86]:
from dateutil.relativedelta import relativedelta
from datetime import datetime

In [87]:
def calculate_total_months(period):
    try:
        start_str, end_str = period.split(' - ')
        start_date = datetime.strptime(start_str, '%b %Y')
        end_date = datetime.strptime(end_str, '%b %Y')
        r = relativedelta(end_date, start_date)
        return r.years * 12 + r.months + 1     # +1 to include the starting month
    except:
        return None

In [88]:
df["Months"]=df["Total Time"].apply(calculate_total_months)

In [89]:
df.head()

,Rank,Title,Score,Episodes,Total Time,Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

Which anime has the highest score

Give top 5 highest scoring anime

Which anime has the highest episode count

Animes with top 5 episode count

Which is the longest running anime