In [66]:
import numpy as np
import pandas as pd

*Loading Data*

In [67]:
df = pd.read_csv(r"C:\Users\prafu\Music\ML-Learning\ML-Playground\Pandas\Practice_Datasets\anime.csv")

In [68]:
df.head()

   Rank                                              Title  Score
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05

**Create a new column for No of Episodes**

In [69]:
df.loc[2]['Title']

'Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 - Dec 2022474,138 members'

*Filtering no of episdoes from title*  
As enclosed inside "()"

In [70]:
def extract_episodes(txt):
    check=False
    data = ""
    for i in txt:
        if i== ")":
            check = False
            return data
        if check == True:
            data += i
        if i=="(":
            check=True

In [74]:
#Applying the funciton
df["Episodes"] = df["Title"].apply(extract_episodes)

In [76]:
df.head()

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10   64 eps
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07   24 eps
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06   13 eps
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06   51 eps
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05   10 eps

Remove " eps" from Episodes  
Type conversion from str to int

In [77]:

df["Episodes"]=df["Episodes"].str.replace(" eps","").astype(int)

In [80]:
df.head()

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10